repos:
  - repo: https://github.com/mxab/pre-commit-trivy.git
    rev: v0.12.0
    hooks:
      - id: trivyfs-docker
        args:
          - --scanners
          - secret
          - --secret-config
          - /src/trivy-secret.yaml
          - --skip-dirs
          - /src/target
          - --skip-dirs
          - /src/.idea
          - --skip-dirs
          - /src/venv
          - --skip-files
          - /src/e2e/docker/localstack/kms/seed.yaml
          - .
